version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight-booking-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    command: npm run start:dev

  db:
    image: postgres:15-alpine
    container_name: flight-booking-db
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: